# Generated by Django 4.1.4 on 2023-06-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
