# Generated by Django 4.1.4 on 2023-02-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubgroup",
            name="description",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
    ]
