# Generated by Django 4.1.4 on 2023-02-03 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("logics", "0003_alter_product_members_poll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="members_poll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="logics.membervote",
            ),
        ),
    ]
