# Generated by Django 4.1.4 on 2023-02-03 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logics", "0004_alter_product_members_poll"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membervote",
            name="vote_count",
        ),
        migrations.RemoveField(
            model_name="membervote",
            name="vote_product_id",
        ),
        migrations.RemoveField(
            model_name="product",
            name="members_poll",
        ),
        migrations.AddField(
            model_name="membervote",
            name="vote_product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="logics.product",
            ),
        ),
        migrations.AddField(
            model_name="membervote",
            name="voter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="vote_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
