# Generated by Django 4.1.4 on 2023-04-07 12:26

from django.db import migrations, models
import logics.models


class Migration(migrations.Migration):

    dependencies = [
        ("logics", "0005_remove_membervote_vote_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubgroup",
            name="club_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=logics.models.ClubGroup.upload_location,
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="clubgroup",
            name="subscription",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=65),
        ),
        migrations.AddField(
            model_name="product",
            name="product_mage",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=logics.models.Product.upload_location,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
    ]
