# Generated by Django 4.1.4 on 2023-06-08 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logics", "0008_clubhousemember_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubhousemember",
            name="subscription_expiration_date",
        ),
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="clubhousemember",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="clubhousemember",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="logics.clubgroup"
            ),
        ),
        migrations.AlterField(
            model_name="clubhousemember",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ClubhouseMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=1000)),
                ("subscription_duration", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "clubhouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_membership",
                        to="logics.clubgroup",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="clubhousemember",
            name="subscription_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership",
                to="logics.clubhousemembership",
            ),
        ),
    ]
