# Generated by Django 4.1.4 on 2023-06-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logics", "0009_remove_clubhousemember_subscription_expiration_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
