# Generated by Django 4.1.4 on 2023-06-08 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("logics", "0010_productcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="products_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_category",
                to="logics.productcategory",
            ),
        ),
    ]
